name: "action-semantic-release"
description: "GitHub action to auto-magically perform semantic version bumps and create releases."
author: "mateothegreat"
branding:
  icon: "box"
  color: "purple"
inputs:
  github_token:
    required: true
    description: "GitHub token with repo permissions."
  owner:
    required: true
    description: "The owner of this repository."
  repo:
    required: true
    description: "The name of this repository."
  default:
    required: false
    description: "The default tag if there are no tags (defaults to 0.0.0)."
  prefix:
    required: false
    description: "Prefix to add to the semantic version value (defaults to none)."
  increment:
    required: true
    description: "Increment based on major, minor, or release."
  branch:
    required: false
    description: "Branch to base tag off of (defaults to main)."
  release_name:
    required: false
    description: "Name of the release (defaults to the new version)."
  release_body:
    required: false
    description: "Body of the release."
  release_notes:
    required: false
    description: "Automatically generate release notes for the release (it will be appended to the body if it is set)."
  committer_name:
    required: true
    description: "Name of the committer."
  committer_email:
    required: true
    description: "Email of the committer."
outputs:
  current_version:
    description: "Current (previous) version (i.e.: 0.0.1)."
  next_version:
    description: "Next (applied) version (i.e.: 0.0.2)."
runs:
  using: "node16"
  main: "dist/index.js"
